# Quick demonstration for Embedded Open Source Summit 2024 Seattle
# list of kernel modules to build, separeted by spaces
obj-m +=  hello.o
# You will clean up whatever is "installed" yourself. We aim for education and simplicity
